info:
  version: 1.0.2
  description: SMF initial local configuration

configuration:
  smfName: SMF
  sbi:
    scheme: http
    registerIPv4: smf.free5gc.org # IP used to register to NRF
    bindingIPv4: smf.free5gc.org  # IP used to bind the service
    port: 8000
    tls:
      key: free5gc/support/TLS/smf.key
      pem: free5gc/support/TLS/smf.pem
  serviceNameList:
    - nsmf-pdusession
    - nsmf-event-exposure
    - nsmf-oam
  snssaiInfos:
    - sNssai:
        sst: 1
        sd: 010203
      dnnInfos:
        - dnn: internet
          dns: 
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
  plmnList:
    - mcc: "208"
      mnc: "93"
  pfcp:
    addr: smf.free5gc.org
  userplane_information:
    up_nodes:
      gNB:
        type: AN

      BranchingUPF:
        type: UPF
        node_id: upfb.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: internet
        interfaces:
          - interfaceType: N3
            endpoints:
              - upfb.free5gc.org
            networkInstance: internet
          - interfaceType: N9
            endpoints:
              - upfb.free5gc.org
            networkInstance: internet

      AnchorUPF1:
        type: UPF
        node_id: upf1.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
               - dnn: internet
                 pools:
                  - cidr: 60.60.0.0/16
        interfaces:
          - interfaceType: N9
            endpoints:
              - upf1.free5gc.org
            networkInstance: internet

      AnchorUPF2:
        type: UPF
        node_id: upf2.free5gc.org
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: internet
        interfaces:
          - interfaceType: N9
            endpoints:
              - upf2.free5gc.org
            networkInstance: internet
    links:
      - A: gNB
        B: BranchingUPF
      - A: BranchingUPF
        B: AnchorUPF1
      - A: BranchingUPF
        B: AnchorUPF2
  nrfUri: http://nrf.free5gc.org:8000
  locality: area1
  ulcl: true

logger:
  SMF:
    debugLevel: info
    ReportCaller: false
  NAS:
    debugLevel: info
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
  PFCP:
    debugLevel: info
    ReportCaller: false