info:
  version: 1.0.0
  description: Routing information for UE

ueRoutingInfo: # the list of UE routing information
  - SUPI: imsi-208930000000003 # Subscription Permanent Identifier of the UE
    AN: gnb1 # the IP address of RAN
    PathList: # the pre-config paths for this SUPI
      - DestinationIP: 142.250.183.206 # the destination IP address on Data Network (DN)
        # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
        # The UPF's name should be consistent with smfcfg.yaml
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2

      - DestinationIP: 142.250.192.142 # the destination IP address on Data Network (DN)
        # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
        # The UPF's name should be consistent with smfcfg.yaml
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2

  - SUPI: imsi-208930000000004 # Subscription Permanent Identifier of the UE
    AN: gnb1 # the IP address of RAN
    PathList: # the pre-config paths for this SUPI
      - DestinationIP: 142.250.192.142   # the destination IP address on Data Network (DN)
        # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
        # The UPF's name should be consistent with smfcfg.yaml
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 142.250.183.206 # the destination IP address on Data Network (DN)
        # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
        # The UPF's name should be consistent with smfcfg.yaml
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2
