info:
  version: 1.0.0
  description: UPF configuration

configuration:
  # debugLevel: panic|fatal|error|warn|info|debug|trace
  debugLevel: info

  pfcp:
    - addr: upfb.free5gc.org

  gtpu:
    - addr: upfb.free5gc.org
    # [optional] gtpu.name
    # - name: upf.5gc.nctu.me
    # [optional] gtpu.ifname
    # - ifname: gtpif

  dnn_list:
    - dnn: intranet
      cidr: 12.1.1.0/24
      # [optional] apn_list[*].natifname
      # natifname: eth0